import axios from 'axios';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

import Track from '../components/Track'


export async function getStaticProps() {
  const response = (await axios.get('http://localhost:3000/api/chart')).data;
  if (!response) return { notFound: true };
  return { props: { tracks: response.tracks.data } };
}

export default function Home({ tracks }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Web Deezer Beta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/favicon.svg" />
      </Head>
      <div className={styles.content}>
        <div className={styles.background_black}>
          <h2 className={styles.title_content}>Principal</h2>
          <div id="backgroundList" className={styles.background_white} styleloading="lazy">
            {tracks.map(track => <Track artist={track.artist.name} cover={track.album.cover} track={track.title} duration={track.duration} album={track.album.title} />)}
          </div>
        </div>
      </div>
    </div>
  )
}