import axios from 'axios';
import { useState, useEffect } from 'react';

import Head from 'next/head';
import styles from '../styles/Home.module.css';

import Track from '../components/Track'
import SearchInput from '../components/SearchInput';
import getDataList from '../pages/api/search';

export async function getStaticProps() {
  const response = (await axios.get('http://localhost:3000/api/chart')).data;
  if (!response) return { notFound: true };
  return { props: { tracks: response.tracks.data } };
}

export async function getStaticPropsSearch() {
  const response = (await axios.get('http://localhost:3000/api/search')).data;
  if (!response) return { notFound: true };
  return { props: { data: response.data } };
}

export default function Home({ tracks }) {
  const [text, setText] = useState('');
  console.log(text)
  
  useEffect(() => {
    if (text) {
      getDataList()
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Web Deezer Beta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/favicon.svg" />
      </Head>

      <div className={styles.search}>
        <div className={styles.form_group}>
          {/* <input
            className={styles.input_group}
            type="text" id="form-title"
            placeholder="Artist, Track, Album..."
          /> */}

          <SearchInput id="search-input" value={text} onChange={(search) => setText(search)} />

          {/* <button className={styles.new_track_btn} type="submit" id="add-btn">Search</button> */}
        </div>
      </div>

      <div className={styles.content}>
        <div className={styles.background_black}>
          <h2 className={styles.title_content}>Principal</h2>
          <div id="backgroundList" className={styles.background_white} styleloading="lazy">
            {tracks.map(track => <Track artist={track.artist.name} cover={track.album.cover} track={track.title} duration={track.duration} album={track.album.title} preview={track.preview} link={track.link} />)}
          </div>
        </div>
      </div>
    </div>
  )
}