import axios from 'axios';
import { useState, useEffect } from 'react';

import Head from 'next/head';
import styles from '../styles/Home.module.css';

import SearchInput from '../components/SearchInput';
import MainTracks from '../components/MainTracks';
import SearchResults from '../components/SearchResults';

export async function getStaticProps() {
  const response = (await axios.get('http://localhost:3000/api/chart')).data;
  if (!response) return { notFound: true };
  return { props: { tracks: response.tracks.data } };
}

export default function Home({ tracks }) {
  const [searchText, setSearchText] = useState('');
  const [searchResults, setSearchResults] = useState([]);

  const doSearch = async (search) => {
    setSearchText(search);
    const response = (await axios.post('http://localhost:3000/api/search', { search })).data;
    console.log(response);
    setSearchResults(response);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Web Deezer Beta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/favicon.svg" />
      </Head>

      <div className={styles.search}>
        <div className={styles.form_group}>
          <SearchInput id="search-input" value={searchText} onChange={(search) => doSearch(search)} />
        </div>
      </div>

      <div className={styles.content}>
        <div className={styles.background_black}>
          <h2 className={styles.title_content}>Principal</h2>
          <div id="backgroundList" className={styles.background_white} styleloading="lazy">
            {searchResults.length ? <SearchResults results={searchResults} /> : <MainTracks tracks={tracks} />}
          </div>
        </div>
      </div>
    </div>
  )
}