import axios from 'axios';

import Head from 'next/head'
import styles from '../../styles/Favorite.module.css'

import FavoriteTracks from '../../components/FavoriteTracks';

export async function getStaticProps() {
    const response = (await axios.get('http://localhost:3000/api/chart')).data;
    if (!response) return { notFound: true };
    return { props: { tracks: response.tracks.data } };
}

export default function Favorite({ tracks }) {

    return (
        <div className={styles.container}>
            <Head>
                <title>Web Deezer Beta</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="shortcut icon" href="./favicon.svg" />
            </Head>

            <div className={styles.content}>
                <div className={styles.background_black}>
                    <h2 className={styles.title_content}>Favorite Tracks</h2>
                    <div id="backgroundList" className={styles.background_white} styleloading="lazy">
                        {/* {tracks.map(track => <FavoriteTracks key={track.id} artist={track.artist.name} cover={track.album.cover} track={track.title} duration={track.duration} album={track.album.title} preview={track.preview} link={track.link} />)} */}
                    </div>
                </div>
            </div>
        </div>
    )
}
