import { useEffect, useState } from 'react';

import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { getTracks } from '../services/DeezerAPI';

export default function Home() {
  const [tracks, setTracks] = useState([]);

  useEffect(() => {
    async function retrieveTracks() {
      if (!tracks.length) {
        const _tracks = await getTracks();
        setTracks(_tracks.data);
      }
    }
    retrieveTracks();
  }, [tracks]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Web Deezer Beta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="./favicon.svg"/>
      </Head>

      <div className={styles.content}>
        <div className={styles.background_black}>
          <h2 className={styles.title_content}>Principal</h2>
          <div id="backgroundList" className={styles.background_white} styleloading="lazy">
            {tracks.map(track => <p>{track.artist.name} - isso é pra testar só</p>)}
          </div>
        </div>
      </div>
    </div>
  )
}
